language: go

go:
  - tip
  - "1.11.4"
  - "1.10.7"
  - 1.9.7
  - 1.8.7
  - 1.7.6
  - 1.6.4

matrix:
  allow_failures:
    - go: tip

addons:
  apt:
    packages:
      - automake
      - libtool
      - libgcrypt11-dev
      - libgpg-error-dev

install: make deps
script: make ci

cache:
  apt:

